/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomPathsRouteImport } from './routes/custom-paths'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicTopicIdRouteImport } from './routes/topic.$topicId'
import { Route as PortfolioUsernameRouteImport } from './routes/portfolio.$username'
import { Route as PathsCreateRouteImport } from './routes/paths.create'
import { Route as AdminRoadmapRouteImport } from './routes/admin.roadmap'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth.github.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomPathsRoute = CustomPathsRouteImport.update({
  id: '/custom-paths',
  path: '/custom-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicIdRoute = TopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioUsernameRoute = PortfolioUsernameRouteImport.update({
  id: '/portfolio/$username',
  path: '/portfolio/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsCreateRoute = PathsCreateRouteImport.update({
  id: '/paths/create',
  path: '/paths/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoadmapRoute = AdminRoadmapRouteImport.update({
  id: '/admin/roadmap',
  path: '/admin/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/auth/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/custom-paths': typeof CustomPathsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRoute
  '/review': typeof ReviewRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/paths/create': typeof PathsCreateRoute
  '/portfolio/$username': typeof PortfolioUsernameRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/custom-paths': typeof CustomPathsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRoute
  '/review': typeof ReviewRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/paths/create': typeof PathsCreateRoute
  '/portfolio/$username': typeof PortfolioUsernameRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/custom-paths': typeof CustomPathsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRoute
  '/review': typeof ReviewRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/paths/create': typeof PathsCreateRoute
  '/portfolio/$username': typeof PortfolioUsernameRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/custom-paths'
    | '/dashboard'
    | '/discover'
    | '/explore'
    | '/login'
    | '/notes'
    | '/profile'
    | '/progress'
    | '/projects'
    | '/review'
    | '/roadmap'
    | '/settings'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/roadmap'
    | '/paths/create'
    | '/portfolio/$username'
    | '/topic/$topicId'
    | '/auth/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/custom-paths'
    | '/dashboard'
    | '/discover'
    | '/explore'
    | '/login'
    | '/notes'
    | '/profile'
    | '/progress'
    | '/projects'
    | '/review'
    | '/roadmap'
    | '/settings'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/roadmap'
    | '/paths/create'
    | '/portfolio/$username'
    | '/topic/$topicId'
    | '/auth/github/callback'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/custom-paths'
    | '/dashboard'
    | '/discover'
    | '/explore'
    | '/login'
    | '/notes'
    | '/profile'
    | '/progress'
    | '/projects'
    | '/review'
    | '/roadmap'
    | '/settings'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/roadmap'
    | '/paths/create'
    | '/portfolio/$username'
    | '/topic/$topicId'
    | '/auth/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRoute
  CustomPathsRoute: typeof CustomPathsRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ProjectsRoute: typeof ProjectsRoute
  ReviewRoute: typeof ReviewRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRoadmapRoute: typeof AdminRoadmapRoute
  PathsCreateRoute: typeof PathsCreateRoute
  PortfolioUsernameRoute: typeof PortfolioUsernameRoute
  TopicTopicIdRoute: typeof TopicTopicIdRoute
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-paths': {
      id: '/custom-paths'
      path: '/custom-paths'
      fullPath: '/custom-paths'
      preLoaderRoute: typeof CustomPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$username': {
      id: '/portfolio/$username'
      path: '/portfolio/$username'
      fullPath: '/portfolio/$username'
      preLoaderRoute: typeof PortfolioUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/create': {
      id: '/paths/create'
      path: '/paths/create'
      fullPath: '/paths/create'
      preLoaderRoute: typeof PathsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roadmap': {
      id: '/admin/roadmap'
      path: '/admin/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof AdminRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRoute,
  CustomPathsRoute: CustomPathsRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ProjectsRoute: ProjectsRoute,
  ReviewRoute: ReviewRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRoadmapRoute: AdminRoadmapRoute,
  PathsCreateRoute: PathsCreateRoute,
  PortfolioUsernameRoute: PortfolioUsernameRoute,
  TopicTopicIdRoute: TopicTopicIdRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
