# Generated by Django 4.2.16 on 2026-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_topicnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="dependents", to="core.topic"
            ),
        ),
    ]
