# Generated by Django 4.2.16 on 2026-06-13 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_notedocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contribution",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="date",
        ),
        migrations.AddField(
            model_name="contribution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
