# Generated by Django 4.2.16 on 2026-06-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github_username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
