# Generated by Django 4.2.16 on 2026-06-15 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_verifiedproject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningpath",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="learningpath",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="estimated_weeks",
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="original_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clones",
                to="core.learningpath",
            ),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("shared", "Shared"),
                ],
                default="private",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PathSharing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("edit", "Can Edit"),
                            ("admin", "Admin"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_with_users",
                        to="core.learningpath",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_paths_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_paths_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("path", "shared_to")},
            },
        ),
    ]
