# Generated by Django 4.2.16 on 2026-06-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_topicscreenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifiedproject",
            name="ai_score",
            field=models.IntegerField(default=0),
        ),
    ]
