# Generated by Django 4.2.16 on 2026-06-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_verifiedproject_ai_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicmaterial",
            name="ai_score",
            field=models.IntegerField(default=0),
        ),
    ]
