# Generated by Django 4.2.16 on 2026-06-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_topicmaterial_ai_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="streak_revive_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
