# Generated by Django 4.2.16 on 2026-06-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_userprofile_streak_revive_used_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="node_kind",
            field=models.CharField(
                choices=[
                    ("milestone", "Milestone"),
                    ("topic", "Topic"),
                    ("optional", "Optional"),
                ],
                default="topic",
                max_length=20,
            ),
        ),
    ]
