# Generated by Django 4.2.16 on 2026-06-16 02:18

from django.db import migrations

def migrate_legacy_paths(apps, schema_editor):
    LearningPath = apps.get_model('core', 'LearningPath')
    Topic = apps.get_model('core', 'Topic')
    
    paths = LearningPath.objects.all()
    for p in paths:
        topics = list(p.topics.all().order_by('order', 'id'))
        if not topics:
            continue
            
        # Check if this path already has ANY milestones
        has_milestones = any(t.node_kind == 'milestone' for t in topics)
        if has_milestones:
            # Just clear explicit dependencies
            for t in topics:
                t.dependencies.clear()
            continue
            
        # Migrate legacy path
        for idx, t in enumerate(topics):
            deps_count = t.dependencies.count()
            if idx == 0:
                t.node_kind = 'milestone'
            elif deps_count > 1:
                t.node_kind = 'milestone'
            else:
                t.node_kind = 'topic'
            t.save()
            t.dependencies.clear()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_topic_node_kind"),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_paths),
    ]
