# Generated by Django 4.2.16 on 2026-06-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_cleanup_legacy_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="selected_title",
            field=models.CharField(default="Novice", max_length=100),
        ),
    ]
