# Generated by Django 4.2.16 on 2026-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_otpverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github_access_token",
            field=models.TextField(blank=True, default=""),
        ),
    ]
