# Generated by Django 4.2.16 on 2026-06-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_userprofile_github_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpath",
            name="github_repo_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
