# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_learningpath_github_repo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningpath",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
