# Generated by Django 4.2.16 on 2026-06-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_flashcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicflashcard",
            name="quality_rating",
            field=models.IntegerField(default=0, help_text="0=unrated, 1=good, -1=bad"),
        ),
    ]
