# Generated by Django 4.2.16 on 2026-06-24 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0028_flashcard_quality_rating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="topicprogress",
            unique_together={("user", "topic")},
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["user", "action_type", "created_at"],
                name="contrib_user_action_date",
            ),
        ),
        migrations.AddIndex(
            model_name="topicprogress",
            index=models.Index(
                fields=["user", "status"], name="topicprogress_user_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contribution",
            constraint=models.CheckConstraint(
                check=models.Q(("points__gte", 0)),
                name="contribution_points_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="topicmaterial",
            constraint=models.CheckConstraint(
                check=models.Q(("ai_score__gte", 0), ("ai_score__lte", 100)),
                name="topicmaterial_ai_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="verifiedproject",
            constraint=models.CheckConstraint(
                check=models.Q(("ai_score__gte", 0), ("ai_score__lte", 100)),
                name="verifiedproject_ai_score_range",
            ),
        ),
    ]
