export type Rarity = "common" | "uncommon" | "rare" | "epic" | "legendary" | "mythic";

export interface TitleTag {
  id: string;
  name: string;
  levelReq: number;
  rarity: Rarity;
  desc: string;
}

export const TITLES: TitleTag[] = [
  // LEVEL 1 - 4 (Common)
  {
    id: "novice",
    name: "Novice",
    levelReq: 1,
    rarity: "common",
    desc: "Just starting the journey.",
  },
  {
    id: "initiate",
    name: "Initiate",
    levelReq: 1,
    rarity: "common",
    desc: "Taking the first steps into the code.",
  },
  {
    id: "rookie",
    name: "Rookie",
    levelReq: 2,
    rarity: "common",
    desc: "Getting a feel for the syntax.",
  },
  {
    id: "apprentice",
    name: "Apprentice",
    levelReq: 2,
    rarity: "common",
    desc: "Learning the fundamental principles.",
  },
  {
    id: "scripter",
    name: "Scripter",
    levelReq: 3,
    rarity: "common",
    desc: "Writing basic scripts.",
  },
  {
    id: "learner",
    name: "Learner",
    levelReq: 3,
    rarity: "common",
    desc: "Absorbing knowledge daily.",
  },
  {
    id: "tinkerer",
    name: "Tinkerer",
    levelReq: 4,
    rarity: "common",
    desc: "Breaking things to see how they work.",
  },
  {
    id: "explorer",
    name: "Explorer",
    levelReq: 4,
    rarity: "common",
    desc: "Mapping out the tech landscape.",
  },

  // LEVEL 5 - 9 (Uncommon)
  {
    id: "adept",
    name: "Adept",
    levelReq: 5,
    rarity: "uncommon",
    desc: "Proficient in the basics.",
  },
  {
    id: "builder",
    name: "Builder",
    levelReq: 5,
    rarity: "uncommon",
    desc: "Assembling working software.",
  },
  { id: "coder", name: "Coder", levelReq: 6, rarity: "uncommon", desc: "Fluent in logic." },
  {
    id: "hacker",
    name: "Hacker",
    levelReq: 6,
    rarity: "uncommon",
    desc: "Finding creative solutions.",
  },
  {
    id: "developer",
    name: "Developer",
    levelReq: 7,
    rarity: "uncommon",
    desc: "Engineering reliable applications.",
  },
  {
    id: "artisan",
    name: "Artisan",
    levelReq: 7,
    rarity: "uncommon",
    desc: "Crafting code with care.",
  },
  {
    id: "technician",
    name: "Technician",
    levelReq: 8,
    rarity: "uncommon",
    desc: "Fixing bugs and maintaining systems.",
  },
  {
    id: "engineer",
    name: "Engineer",
    levelReq: 8,
    rarity: "uncommon",
    desc: "Designing robust architectures.",
  },
  {
    id: "creator",
    name: "Creator",
    levelReq: 9,
    rarity: "uncommon",
    desc: "Bringing ideas to life.",
  },

  // LEVEL 10 - 19 (Rare)
  {
    id: "veteran",
    name: "Veteran",
    levelReq: 10,
    rarity: "rare",
    desc: "Experienced in the trenches.",
  },
  {
    id: "architect",
    name: "Architect",
    levelReq: 11,
    rarity: "rare",
    desc: "Designing the blueprint.",
  },
  {
    id: "specialist",
    name: "Specialist",
    levelReq: 12,
    rarity: "rare",
    desc: "Mastering a specific domain.",
  },
  { id: "innovator", name: "Innovator", levelReq: 13, rarity: "rare", desc: "Pushing boundaries." },
  {
    id: "pioneer",
    name: "Pioneer",
    levelReq: 14,
    rarity: "rare",
    desc: "Venturing into unknown territories.",
  },
  {
    id: "sage",
    name: "Sage",
    levelReq: 15,
    rarity: "rare",
    desc: "Possessing deep technical wisdom.",
  },
  { id: "ninja", name: "Ninja", levelReq: 16, rarity: "rare", desc: "Swift and silent execution." },
  { id: "wizard", name: "Wizard", levelReq: 17, rarity: "rare", desc: "Performing code magic." },
  {
    id: "guru",
    name: "Guru",
    levelReq: 18,
    rarity: "rare",
    desc: "Guiding others through the code.",
  },
  {
    id: "maestro",
    name: "Maestro",
    levelReq: 19,
    rarity: "rare",
    desc: "Orchestrating complex systems.",
  },

  // LEVEL 20 - 29 (Epic)
  {
    id: "master",
    name: "Master",
    levelReq: 20,
    rarity: "epic",
    desc: "Unparalleled skill and dedication.",
  },
  {
    id: "visionary",
    name: "Visionary",
    levelReq: 21,
    rarity: "epic",
    desc: "Seeing the future of tech.",
  },
  {
    id: "champion",
    name: "Champion",
    levelReq: 22,
    rarity: "epic",
    desc: "Overcoming the hardest challenges.",
  },
  { id: "elite", name: "Elite", levelReq: 23, rarity: "epic", desc: "Among the top percent." },
  {
    id: "legend",
    name: "Legend",
    levelReq: 24,
    rarity: "epic",
    desc: "Stories are told of your commits.",
  },
  {
    id: "oracle",
    name: "Oracle",
    levelReq: 25,
    rarity: "epic",
    desc: "Predicting edge cases before they happen.",
  },
  {
    id: "prodigy",
    name: "Prodigy",
    levelReq: 26,
    rarity: "epic",
    desc: "Natural talent refined by hard work.",
  },
  { id: "virtuoso", name: "Virtuoso", levelReq: 27, rarity: "epic", desc: "Flawless execution." },
  { id: "titan", name: "Titan", levelReq: 28, rarity: "epic", desc: "A pillar of the community." },
  {
    id: "luminary",
    name: "Luminary",
    levelReq: 29,
    rarity: "epic",
    desc: "Illuminating the path for others.",
  },

  // LEVEL 30 - 39 (Legendary)
  {
    id: "grandmaster",
    name: "Grandmaster",
    levelReq: 30,
    rarity: "legendary",
    desc: "The highest echelon of mastery.",
  },
  {
    id: "paragon",
    name: "Paragon",
    levelReq: 31,
    rarity: "legendary",
    desc: "The perfect example of excellence.",
  },
  {
    id: "ascendant",
    name: "Ascendant",
    levelReq: 32,
    rarity: "legendary",
    desc: "Rising above all limits.",
  },
  {
    id: "sovereign",
    name: "Sovereign",
    levelReq: 33,
    rarity: "legendary",
    desc: "Ruling the codebase.",
  },
  {
    id: "emissary",
    name: "Emissary",
    levelReq: 34,
    rarity: "legendary",
    desc: "Representing the highest standards.",
  },
  {
    id: "vanguard",
    name: "Vanguard",
    levelReq: 35,
    rarity: "legendary",
    desc: "Leading the charge into the future.",
  },
  {
    id: "sentinel",
    name: "Sentinel",
    levelReq: 36,
    rarity: "legendary",
    desc: "Guarding the system with unwavering focus.",
  },
  {
    id: "weaver",
    name: "Weaver",
    levelReq: 37,
    rarity: "legendary",
    desc: "Weaving reality through syntax.",
  },
  {
    id: "catalyst",
    name: "Catalyst",
    levelReq: 38,
    rarity: "legendary",
    desc: "Sparking massive change.",
  },
  {
    id: "nexus",
    name: "Nexus",
    levelReq: 39,
    rarity: "legendary",
    desc: "The core of the system.",
  },

  // LEVEL 40+ (Mythic)
  {
    id: "mythic",
    name: "Mythic",
    levelReq: 40,
    rarity: "mythic",
    desc: "Beyond human comprehension.",
  },
  {
    id: "demigod",
    name: "Demigod",
    levelReq: 42,
    rarity: "mythic",
    desc: "Half-human, half-code.",
  },
  {
    id: "immortal",
    name: "Immortal",
    levelReq: 45,
    rarity: "mythic",
    desc: "Your code will live forever.",
  },
  {
    id: "celestial",
    name: "Celestial",
    levelReq: 48,
    rarity: "mythic",
    desc: "Operating on a higher plane.",
  },
  {
    id: "god_tier",
    name: "God Tier",
    levelReq: 50,
    rarity: "mythic",
    desc: "You write the laws of the universe.",
  },
];
